# Change these first
owner: SpotDraft # Your GitHub username
repo: spotdraft_status.github.io  # Your GitHub repository name

# Add your sites here
sites:
  - name: Spotdraft App
    url: https://app.spotdraft.com
  - name: Backend API
    url: https://api.spotdraft.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.spotdraft.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/SpotDraft/spotdraft_status.github.io/master/static/img/logo1.png
  name: Status
  introTitle: "Spotdraft Status Dashboard"
  introMessage: This page provides status information on the services that are part of Spotdraft Platform
  navbar:
    - title: status
      href: /
    - title: Go to App
      href: https://app.spotdraft.com
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration